# Generated by Django 4.2 on 2023-07-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=50)),
                ('leyenda', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Camilla',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('camilla', models.CharField(max_length=50)),
                ('leyenda', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('contrasena', models.IntegerField()),
                ('fk_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.area')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('entrada', models.TimeField()),
                ('salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=50)),
                ('fk_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('sala', models.CharField(max_length=50)),
                ('leyenda', models.CharField(max_length=50)),
                ('fk_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.area')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.CharField(max_length=50)),
                ('completado', models.BooleanField()),
                ('fk_accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.accion')),
                ('fk_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.actividad')),
                ('fk_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.area')),
                ('fk_camilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.camilla')),
                ('fk_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.sala')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fk_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.horario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fk_tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.tipousuario'),
        ),
        migrations.AddField(
            model_name='camilla',
            name='fk_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.sala'),
        ),
    ]
